name: Build Version Once Per PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-version:
    name: Build version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: ./.github/actions/setup-cached-python
        with:
          version: "3.9"

      - name: Bump the version number
        run: inv update-build-number

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bump the build number
